# Generated by Django 4.2.28 on 2026-02-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Всего запросов')),
                ('successful_requests', models.IntegerField(default=0, verbose_name='Успешных запросов')),
                ('failed_requests', models.IntegerField(default=0, verbose_name='Неудачных запросов')),
                ('total_users', models.IntegerField(default=0, verbose_name='Всего пользователей')),
                ('active_users', models.IntegerField(default=0, verbose_name='Активных пользователей')),
                ('avg_processing_time', models.FloatField(default=0.0, verbose_name='Среднее время обработки (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Статистика дашборда',
                'verbose_name_plural': 'Статистика дашборда',
                'ordering': ['-date'],
            },
        ),
    ]
