# Generated by Django 4.2.28 on 2026-02-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardStats',
        ),
    ]
