# Generated by Django 4.2.28 on 2026-04-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metapko', '0004_rename_metapko_cal_starts__e2ce53_idx_metapko_cal_starts__38b0c9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Ошибка'), ('warning', 'Предупреждение')], max_length=20)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_load_hours', models.PositiveIntegerField(default=20, verbose_name='Максимальная нагрузка')),
                ('specializations', models.ManyToManyField(blank=True, to='metapko.course')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_profile', to='metapko.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveIntegerField(default=20, verbose_name='Студентов')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_profile', to='metapko.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hours', models.PositiveIntegerField(default=32, verbose_name='Часов в семестре')),
                ('course_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная')], default='lecture', max_length=20, verbose_name='Тип')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_profile', to='metapko.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metapko.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metapko.teacher')),
            ],
        ),
    ]
