# Generated by Django 4.2.28 on 2026-04-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='academic_degree',
            field=models.CharField(choices=[('none', 'Без степени'), ('master', 'Магистр'), ('candidate', 'Кандидат наук'), ('doctor', 'Доктор наук'), ('phd', 'PhD')], default='none', max_length=20, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='employment_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='max_load_hours',
            field=models.PositiveIntegerField(default=20, verbose_name='Максимальная нагрузка (ч/нед)'),
        ),
    ]
