# Generated by Django 4.2.28 on 2026-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_teacherprofile_academic_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_degree',
            field=models.CharField(choices=[('none', 'Без степени'), ('master', 'Магистр'), ('phd', 'PhD'), ('assoc_prof', 'Асоц. профессор'), ('professor', 'Профессор'), ('research_prof', 'Профессор-исследователь')], default='none', max_length=20, verbose_name='Ученая степень'),
        ),
    ]
