# Generated by Django 4.2.28 on 2026-02-11 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код языка')),
                ('name', models.CharField(max_length=100, verbose_name='Название языка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OCRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ настройки')),
                ('value', models.TextField(verbose_name='Значение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройка OCR',
                'verbose_name_plural': 'Настройки OCR',
            },
        ),
        migrations.CreateModel(
            name='OCRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ocr_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('recognized_text', models.TextField(blank=True, verbose_name='Распознанный текст')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Точность распознавания')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Время обработки (сек)')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_requests', to='ocr.language', verbose_name='Язык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'OCR запрос',
                'verbose_name_plural': 'OCR запросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
