# Generated by Django 4.2.28 on 2026-04-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_recognitionhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recognitionhistory',
            new_name='ocr_recogni_user_id_24ce6e_idx',
            old_name='ocr_recogn_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='recognitionhistory',
            new_name='ocr_recogni_languag_4f1696_idx',
            old_name='ocr_recogn_language_idx',
        ),
        migrations.RenameIndex(
            model_name='recognitionhistory',
            new_name='ocr_recogni_is_favo_7c6adf_idx',
            old_name='ocr_recogn_is_favor_idx',
        ),
    ]
