"""Тестовые вакансии и метаданные категорий для демо-макета (без БД)."""

CATEGORY_META = {
    'it': {'label': 'IT и digital', 'color': '#0d9488'},
    'sales': {'label': 'Продажи', 'color': '#ea580c'},
    'marketing': {'label': 'Маркетинг', 'color': '#db2777'},
    'finance': {'label': 'Финансы и учёт', 'color': '#4f46e5'},
    'logistics': {'label': 'Логистика', 'color': '#b45309'},
    'edu': {'label': 'Образование', 'color': '#2563eb'},
    'hr': {'label': 'HR', 'color': '#7c3aed'},
    'medical': {'label': 'Медицина', 'color': '#e11d48'},
    'construction': {'label': 'Строительство', 'color': '#ca8a04'},
    'hospitality': {'label': 'HoReCa', 'color': '#dc2626'},
    'legal': {'label': 'Юриспруденция', 'color': '#4338ca'},
    'agro': {'label': 'Агро', 'color': '#15803d'},
    'production': {'label': 'Производство', 'color': '#57534e'},
    'security': {'label': 'Безопасность', 'color': '#1e3a5f'},
    'retail': {'label': 'Ритейл', 'color': '#c026d3'},
    'auto': {'label': 'Авто', 'color': '#0f172a'},
    'support': {'label': 'Поддержка', 'color': '#0891b2'},
    'creative': {'label': 'Креатив', 'color': '#be185d'},
    'science': {'label': 'Наука / лаб', 'color': '#0369a1'},
    'ecommerce': {'label': 'E-commerce', 'color': '#7c2d12'},
    'purchase': {'label': 'Закупки', 'color': '#a16207'},
}

MOCK_VACANCIES = [
    {
        'slug': 'python-middle-almaty',
        'title': 'Python-разработчик (middle)',
        'company': 'ТОО «Цифровые решения»',
        'city': 'Алматы',
        'salary': 'от 800 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис / гибрид',
        'category': 'it',
        'tags': ['Python', 'Django', 'PostgreSQL'],
        'posted': '21.03.2026',
        'description': 'Развитие внутренних сервисов компании, REST API, интеграции. Опыт от 3 лет, знание SQL и Git.',
    },
    {
        'slug': 'sales-b2b-astana',
        'title': 'Менеджер по продажам B2B',
        'company': 'АО «КазТрейд»',
        'city': 'Астана',
        'salary': '350 000 ₸ + %',
        'employment': 'полная занятость',
        'format': 'гибрид',
        'category': 'sales',
        'tags': ['B2B', 'CRM', 'переговоры'],
        'posted': '20.03.2026',
        'description': 'Работа с корпоративными клиентами, ведение воронки, участие в тендерах. Опыт в продажах от 2 лет.',
    },
    {
        'slug': 'ui-ux-remote',
        'title': 'Дизайнер интерфейсов (UI/UX)',
        'company': 'Стартап NomadLab',
        'city': 'Удалённо',
        'salary': 'по договорённости',
        'employment': 'проект 6 мес.',
        'format': 'удалённо',
        'category': 'it',
        'tags': ['Figma', 'UI Kit', 'исследования'],
        'posted': '19.03.2026',
        'description': 'Дизайн веб- и мобильных интерфейсов, прототипы, передача в разработку. Портфолио обязательно.',
    },
    {
        'slug': 'devops-engineer',
        'title': 'DevOps-инженер',
        'company': 'ТОО «Облако KZ»',
        'city': 'Алматы',
        'salary': 'от 900 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис',
        'category': 'it',
        'tags': ['Kubernetes', 'CI/CD', 'Linux'],
        'posted': '18.03.2026',
        'description': 'Поддержка инфраструктуры, автоматизация деплоя, мониторинг. Docker, Ansible — плюс.',
    },
    {
        'slug': 'accountant',
        'title': 'Главный бухгалтер',
        'company': 'ИП «Степь Логистик»',
        'city': 'Шымкент',
        'salary': '450 000 – 550 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис',
        'category': 'finance',
        'tags': ['1С', 'НДС', 'отчётность'],
        'posted': '17.03.2026',
        'description': 'Полное ведение учёта, зарплата, налоговая отчётность. Опыт в логистике приветствуется.',
    },
    {
        'slug': 'marketing-smm',
        'title': 'Маркетолог / SMM',
        'company': 'Retail Group «Алатау»',
        'city': 'Алматы',
        'salary': 'от 400 000 ₸',
        'employment': 'полная занятость',
        'format': 'гибрид',
        'category': 'marketing',
        'tags': ['Instagram', 'таргет', 'аналитика'],
        'posted': '16.03.2026',
        'description': 'Контент-план, рекламные кампании, взаимодействие с подрядчиками. Ритейл — преимущество.',
    },
    {
        'slug': 'teacher-english',
        'title': 'Преподаватель английского',
        'company': 'Языковой центр «Tildes»',
        'city': 'Караганда',
        'salary': 'от 280 000 ₸',
        'employment': 'частичная / полная',
        'format': 'офис',
        'category': 'edu',
        'tags': ['B2', 'дети', 'группы'],
        'posted': '15.03.2026',
        'description': 'Группы взрослых и подростков, методика коммуникативная. Сертификат CELTA или аналог — плюс.',
    },
    {
        'slug': 'warehouse-lead',
        'title': 'Руководитель склада',
        'company': 'ТОО «Евразия Снаб»',
        'city': 'Астана',
        'salary': '600 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис + склад',
        'category': 'logistics',
        'tags': ['WMS', 'команда 15 чел.'],
        'posted': '14.03.2026',
        'description': 'Учёт остатков, приёмка, отгрузка, дисциплина на складе. Опыт руководства от 2 лет.',
    },
    {
        'slug': 'hr-manager',
        'title': 'HR-менеджер',
        'company': 'ТОО «Qazaq HR»',
        'city': 'Алматы',
        'salary': 'от 420 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис',
        'category': 'hr',
        'tags': ['подбор', 'адаптация', 'HRIS'],
        'posted': '13.03.2026',
        'description': 'Полный цикл подбора, работа с площадками вакансий, внутренние политики компании.',
    },
    {
        'slug': 'data-analyst',
        'title': 'Аналитик данных',
        'company': 'Банк «Дана»',
        'city': 'Алматы',
        'salary': 'от 700 000 ₸',
        'employment': 'полная занятость',
        'format': 'гибрид',
        'category': 'finance',
        'tags': ['SQL', 'Python', 'дашборды'],
        'posted': '12.03.2026',
        'description': 'Отчёты для бизнес-подразделений, визуализация в BI-инструментах. NDA, график 5/2.',
    },
    {
        'slug': 'frontend-react',
        'title': 'Frontend (React)',
        'company': 'ТОО «AppCraft»',
        'city': 'Удалённо',
        'salary': 'от 750 000 ₸',
        'employment': 'полная занятость',
        'format': 'удалённо',
        'category': 'it',
        'tags': ['React', 'TypeScript', 'REST'],
        'posted': '11.03.2026',
        'description': 'SPA для финтех-продукта, код-ревью, дизайн-система. Опыт от 2 лет.',
    },
    {
        'slug': 'driver-c',
        'title': 'Водитель категории C',
        'company': 'ТОО «Транзит KZ»',
        'city': 'Актобе',
        'salary': 'от 350 000 ₸',
        'employment': 'полная занятость',
        'format': 'линия',
        'category': 'logistics',
        'tags': ['межгород', 'опыт 3+ года'],
        'posted': '10.03.2026',
        'description': 'Доставка сборных грузов по региону, сопроводительные документы, сменный график.',
    },
    # —— Дополнительные сферы ——
    {
        'slug': 'nurse-district-almaty',
        'title': 'Медсестра участковая',
        'company': 'ГП №4 Алматы',
        'city': 'Алматы',
        'salary': '320 000 – 380 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис / выезды',
        'category': 'medical',
        'tags': ['участок', 'документы', 'вакцинация'],
        'posted': '22.03.2026',
        'description': 'Работа с амбулаторными картами, процедурный кабинет, взаимодействие с врачами участка.',
    },
    {
        'slug': 'foreman-residential',
        'title': 'Прораб (жилое строительство)',
        'company': 'ТОО «Qurylys Elite»',
        'city': 'Астана',
        'salary': 'от 700 000 ₸',
        'employment': 'полная занятость',
        'format': 'объект + офис',
        'category': 'construction',
        'tags': ['СМР', 'бригады', 'сроки'],
        'posted': '22.03.2026',
        'description': 'Контроль графика, качества и техники безопасности на площадке, приёмка работ подрядчиков.',
    },
    {
        'slug': 'chef-restaurant-alash',
        'title': 'Шеф-повар',
        'company': 'Ресторан «Алаш»',
        'city': 'Алматы',
        'salary': '550 000 – 850 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис (кухня)',
        'category': 'hospitality',
        'tags': ['меню', 'команда', 'HACCP'],
        'posted': '21.03.2026',
        'description': 'Разработка карт, закупка продуктов, обучение линии. Опыт в премиум-сегменте желателен.',
    },
    {
        'slug': 'legal-assistant-tore',
        'title': 'Помощник юриста',
        'company': 'ЮК «Төре»',
        'city': 'Астана',
        'salary': 'от 400 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис',
        'category': 'legal',
        'tags': ['договоры', 'иски', 'КАП'],
        'posted': '21.03.2026',
        'description': 'Подготовка претензий, работа с госреестрами, сопровождение сделок с недвижимостью.',
    },
    {
        'slug': 'agronom-field-kostanay',
        'title': 'Агроном',
        'company': 'ТОО «Ер Тarıмы»',
        'city': 'Костанайская обл.',
        'salary': 'от 380 000 ₸',
        'employment': 'полная занятость',
        'format': 'поле / офис',
        'category': 'agro',
        'tags': ['зерно', 'удобрения', 'учёт'],
        'posted': '20.03.2026',
        'description': 'Планирование посевов, контроль вегетации, взаимодействие с механизаторами и лабораторией.',
    },
    {
        'slug': 'cnc-operator-karaganda',
        'title': 'Оператор станков ЧПУ',
        'company': 'Завод «МеталлПром»',
        'city': 'Караганда',
        'salary': 'от 450 000 ₸',
        'employment': 'сменная занятость',
        'format': 'цех',
        'category': 'production',
        'tags': ['ЧПУ', 'чертежи', 'ОТ'],
        'posted': '20.03.2026',
        'description': 'Наладка, контроль размеров, мелкий ремонт инструмента. Удостоверение по охране труда.',
    },
    {
        'slug': 'mall-security-shymkent',
        'title': 'Специалист службы безопасности (ТЦ)',
        'company': 'ТОО «SecureKZ»',
        'city': 'Шымкент',
        'salary': 'от 280 000 ₸',
        'employment': 'полная занятость',
        'format': 'смены',
        'category': 'security',
        'tags': ['видео', 'патруль', 'КЦ'],
        'posted': '19.03.2026',
        'description': 'Контроль входных групп, работа с тревожной сигнализацией, отчёты по инцидентам.',
    },
    {
        'slug': 'retail-gadget-consultant',
        'title': 'Продавец-консультант (электроника)',
        'company': 'Сеть «GadgetLine»',
        'city': 'Алматы',
        'salary': '220 000 ₸ + %',
        'employment': 'полная занятость',
        'format': 'торговый зал',
        'category': 'retail',
        'tags': ['касса', 'мерчендайзинг', 'гарантия'],
        'posted': '19.03.2026',
        'description': 'Консультирование по смартфонам и аксессуарам, выкладка, участие в инвентаризациях.',
    },
    {
        'slug': 'auto-diagnostic-aktobe',
        'title': 'Автодиагност / механик',
        'company': 'СТО «Жол»',
        'city': 'Актобе',
        'salary': 'от 400 000 ₸',
        'employment': 'полная занятость',
        'format': 'боксы',
        'category': 'auto',
        'tags': ['OBD', 'подвеска', 'ДВС'],
        'posted': '18.03.2026',
        'description': 'Диагностика легкового парка, согласование ремонта с клиентом, отчёт в CRM.',
    },
    {
        'slug': 'support-chat-fintech',
        'title': 'Специалист поддержки L1 (чат)',
        'company': 'Финтех «DalaPay»',
        'city': 'Удалённо',
        'salary': 'от 350 000 ₸',
        'employment': 'полная занятость',
        'format': 'удалённо',
        'category': 'support',
        'tags': ['чат', 'скрипты', 'эскалация'],
        'posted': '18.03.2026',
        'description': 'Ответы пользователям в приложении, фиксация багов, передача сложных кейсов в L2.',
    },
    {
        'slug': 'motion-designer-studio',
        'title': 'Motion-дизайнер',
        'company': 'Студия «Кадр»',
        'city': 'Алматы',
        'salary': 'от 500 000 ₸',
        'employment': 'проект 3 мес.',
        'format': 'гибрид',
        'category': 'creative',
        'tags': ['After Effects', '2D', 'реклама'],
        'posted': '17.03.2026',
        'description': 'Ролики для соцсетей и ТВ-спотов, storyboard, работа с закадровым голосом.',
    },
    {
        'slug': 'lab-chemist-pavlodar',
        'title': 'Химик-лаборант',
        'company': 'ТОО «ФармаСинтез»',
        'city': 'Павлодар',
        'salary': '420 000 – 500 000 ₸',
        'employment': 'полная занятость',
        'format': 'лаборатория',
        'category': 'science',
        'tags': ['ХВО', 'ГОСТ', 'журналы'],
        'posted': '17.03.2026',
        'description': 'Входной контроль сырья, спектрометрия, оформление протоколов для серии.',
    },
    {
        'slug': 'marketplace-manager',
        'title': 'Менеджер маркетплейса',
        'company': 'ТОО «SteppeMart»',
        'city': 'Удалённо',
        'salary': 'от 500 000 ₸ + KPI',
        'employment': 'полная занятость',
        'format': 'удалённо',
        'category': 'ecommerce',
        'tags': ['WB/Kaspi', 'контент', 'остатки'],
        'posted': '16.03.2026',
        'description': 'Ведение карточек, цены и акции, работа с поставками FBO/FBY, отчёты по марже.',
    },
    {
        'slug': 'dentist-assistant-astana',
        'title': 'Ассистент стоматолога',
        'company': 'Клиника «Ақ нұр»',
        'city': 'Астана',
        'salary': 'от 350 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис',
        'category': 'medical',
        'tags': ['стерилизация', '4 руки', 'рентген'],
        'posted': '16.03.2026',
        'description': 'Подготовка кабинета, ассистирование врачу, учёт расходных материалов.',
    },
    {
        'slug': 'tiler-finisher',
        'title': 'Плиточник-отделочник',
        'company': 'ИП на объекте',
        'city': 'Алматы',
        'salary': 'сдельная от 400 000 ₸',
        'employment': 'проект',
        'format': 'объект',
        'category': 'construction',
        'tags': ['керамогранит', 'санузлы'],
        'posted': '15.03.2026',
        'description': 'Жилой комплекс бизнес-класса, график этажей, инструмент предоставляется частично.',
    },
    {
        'slug': 'hotel-reception-shymkent',
        'title': 'Администратор гостиницы',
        'company': 'Hotel «Silk Road»',
        'city': 'Шымкент',
        'salary': 'от 300 000 ₸',
        'employment': 'сменная занятость',
        'format': 'смены 2/2',
        'category': 'hospitality',
        'tags': ['Opera PMS', 'английский', 'заселение'],
        'posted': '15.03.2026',
        'description': 'Работа с бронированиями, конфликтные ситуации, касса и отчётность смены.',
    },
    {
        'slug': 'sourcing-specialist',
        'title': 'Специалист по закупкам',
        'company': 'ТОО «Оптима Снаб»',
        'city': 'Алматы',
        'salary': 'от 480 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис',
        'category': 'purchase',
        'tags': ['тендеры', 'договоры', 'логистика'],
        'posted': '14.03.2026',
        'description': 'Поиск поставщиков, сравнение КП, согласование условий с финансами и юристами.',
    },
    {
        'slug': 'vet-assistant-taraz',
        'title': 'Ассистент ветеринара',
        'company': 'КП «Мал-Аманат»',
        'city': 'Тараз',
        'salary': 'от 290 000 ₸',
        'employment': 'полная занятость',
        'format': 'клиника',
        'category': 'medical',
        'tags': ['мелкие животные', 'вакцинация'],
        'posted': '14.03.2026',
        'description': 'Подготовка животных к процедурам, уход за стационаром, консультации владельцев.',
    },
    {
        'slug': 'forklift-jetlog',
        'title': 'Водитель погрузчика',
        'company': 'Склад «JetLog»',
        'city': 'Астана',
        'salary': 'от 380 000 ₸',
        'employment': 'сменная занятость',
        'format': 'склад',
        'category': 'logistics',
        'tags': ['паллеты', 'учёт WMS'],
        'posted': '13.03.2026',
        'description': 'Приёмка и отгрузка FBS, соблюдение маршрутов внутри склада, медосмотр.',
    },
    {
        'slug': 'barista-coffee-lab',
        'title': 'Бариста',
        'company': 'Сеть «KZ Coffee Lab»',
        'city': 'Алматы',
        'salary': '250 000 ₸ + чаевые',
        'employment': 'полная / частичная',
        'format': 'точка продаж',
        'category': 'hospitality',
        'tags': ['латте-арт', 'обучение', 'касса'],
        'posted': '13.03.2026',
        'description': 'Приготовление напитков по стандартам сети, чистота зоны, участие в капитанских сменах.',
    },
    {
        'slug': 'java-backend-senior',
        'title': 'Java-разработчик (senior)',
        'company': 'ТОО «Nomad FinTech»',
        'city': 'Алматы',
        'salary': 'от 1 100 000 ₸',
        'employment': 'полная занятость',
        'format': 'гибрид',
        'category': 'it',
        'tags': ['Java 17', 'Spring', 'Kafka'],
        'posted': '12.03.2026',
        'description': 'Микросервисы платёжного ядла, код-ревью, онколлы по ротации.',
    },
    {
        'slug': '1c-consultant',
        'title': 'Консультант 1С',
        'company': 'ИТ-интегратор «Баланс»',
        'city': 'Астана',
        'salary': 'от 520 000 ₸',
        'employment': 'полная занятость',
        'format': 'офис / выезды',
        'category': 'finance',
        'tags': ['ERP', 'БУХ', 'доработки'],
        'posted': '12.03.2026',
        'description': 'Внедрение типовых конфигураций, обучение ключевых пользователей, сопровождение.',
    },
    {
        'slug': 'call-center-outbound',
        'title': 'Оператор колл-центра (исход)',
        'company': 'ТОО «Connect Hub»',
        'city': 'Караганда',
        'salary': '180 000 ₸ + бонус',
        'employment': 'полная занятость',
        'format': 'офис',
        'category': 'support',
        'tags': ['скрипты', 'NPS', 'CRM'],
        'posted': '11.03.2026',
        'description': 'Обзвон по базе, фиксация результатов, передача лидов в отдел продаж.',
    },
    {
        'slug': 'photographer-product',
        'title': 'Предметный фотограф',
        'company': 'Студия «Frame»',
        'city': 'Алматы',
        'salary': 'от 380 000 ₸',
        'employment': 'частичная занятость',
        'format': 'студия',
        'category': 'creative',
        'tags': ['свет', 'ретушь', 'e-com'],
        'posted': '11.03.2026',
        'description': 'Съёмка для маркетплейсов, цветопрофили, сдача готовых PSD/PNG по ТЗ.',
    },
    {
        'slug': 'electrician-industrial',
        'title': 'Электромонтёр (пром)',
        'company': 'ТОО «ЭнергоМонтаж»',
        'city': 'Павлодар',
        'salary': 'от 430 000 ₸',
        'employment': 'сменная занятость',
        'format': 'объект',
        'category': 'production',
        'tags': ['до 1000В', 'допуск', 'схемы'],
        'posted': '10.03.2026',
        'description': 'Монтаж силовых линий на производстве, журнал ИТР, взаимодействие с ПТО.',
    },
]


def _enrich_vacancies():
    for v in MOCK_VACANCIES:
        m = CATEGORY_META.get(v['category'], {'label': v['category'], 'color': '#64748b'})
        v['cat_label'] = m['label']
        v['accent_color'] = m['color']


_enrich_vacancies()

UNIQUE_CITIES = sorted({v['city'] for v in MOCK_VACANCIES}, key=lambda c: (c != 'Удалённо', c.lower()))

CATEGORY_OPTIONS = sorted(CATEGORY_META.items(), key=lambda x: x[1]['label'])

# Тестовые учётные записи
MOCK_ACCOUNTS = {
    'seeker': {
        'password': 'demo123',
        'role': 'seeker',
        'display': 'Айдар Нурланов',
        'email': 'seeker@demo.meta-university.kz',
    },
    'employer': {
        'password': 'demo123',
        'role': 'employer',
        'display': 'ТОО «Дана Демо»',
        'email': 'hr@demo.meta-university.kz',
    },
    'admin_demo': {
        'password': 'demo123',
        'role': 'admin',
        'display': 'Администратор',
        'email': 'admin@demo.meta-university.kz',
    },
}

SESSION_KEY = 'job_portal_mock_user'
