# Generated by Django 4.2.28 on 2026-04-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metapko', '0003_programs_buildings_calendar_news_contacts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='metapko_cal_starts__38b0c9_idx',
            old_name='metapko_cal_starts__e2ce53_idx',
        ),
        migrations.RenameIndex(
            model_name='classsession',
            new_name='metapko_cla_starts__807eb8_idx',
            old_name='metapko_cla_starts__idx',
        ),
        migrations.RenameIndex(
            model_name='customerorder',
            new_name='metapko_cus_status_675f3d_idx',
            old_name='metapko_cus_status__idx',
        ),
        migrations.RenameIndex(
            model_name='serviceticket',
            new_name='metapko_ser_status_7d1974_idx',
            old_name='metapko_ser_status__idx',
        ),
    ]
